language: python

install:
- travis_retry pip install -r requirements-dev.txt
- travis_retry pip install -r requirements.txt
- travis_retry pip install -e .

script:
- python -m unittest discover

script:
- cd crash4viz/tests
- pytest test_ml.py


after_success:
- coveralls