language: python

install:
- travis_retry pip install -r requirements-dev.txt
- travis_retry pip install -r requirements.txt
- travis_retry pip install -e .

script:
- flake8
- cd crash4viz/tests
- pytest test_ml.py
# - python -m unittest discover

after_success:
- coveralls