language: python

install:
# - travis_retry pip install -r requirements-dev.txt
- travis_retry pip install -r requirements.txt
- travis_retry pip install -e .

script:
- coverage run -m unittest discover


after_success:
- coveralls